### ISSUE TITLE
Make fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by mrigger** [stephenrkell/liballocs#10]
I tried to build liballocs to use it with libcrunch, but the `make` step failed. To make the issue reproducible, I created a `Dockerfile`: 

```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y bison flex texinfo git build-essential
RUN git clone https://github.com/stephenrkell/binutils-gdb.git
RUN cd binutils-gdb && \
   chmod +x configure && \
   CFLAGS="-fPIC -g -O2" ./configure --prefix=/usr/local \
     --enable-gold --enable-plugins --enable-install-libiberty && \
   make -j4 && make install
RUN apt-get update && \
   apt-get install -y libelf-dev \
       autoconf automake libtool pkg-config autoconf-archive \
       g++ ocaml ocaml-findlib \
       default-jre-headless \
       make git gawk gdb \
       libunwind-dev libc6-dev-i386 zlib1g-dev libc6-dbg \
       libboost-iostreams-dev libboost-regex-dev libboost-serialization-dev libboost-filesystem-dev
RUN git clone https://github.com/stephenrkell/liballocs.git
RUN apt-get update && apt-get install -y python
RUN cd liballocs && \
   git submodule init && \
   git submodule update && \
   make -C contrib -j1
```
The last step fails with the following error message:
```
libtool: compile:  g++ -DPACKAGE_NAME=\"libdwarfpp\" -DPACKAGE_TARNAME=\"libdwarfpp\" -DPACKAGE_VERSION=\"0.1\" "-DPACKAGE_STRING=\"libdwarfpp 0.1\"" -DPACKAGE_BUGREPORT=\"srk31@cl.cam.ac.uk\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DPACKAGE=\"libdwarfpp\" -DVERSION=\"0.1\" -DHAVE_CXX14=1 -DHAVE_PTRDIFF_T=1 -DHAVE_ALGORITHM=1 -DHAVE_CASSERT=1 -DHAVE_CSTDLIB=1 -DHAVE_ELF_H=1 -DHAVE_FUNCTIONAL=1 -DHAVE_IOSTREAM=1 -DHAVE_ITERATOR=1 -DHAVE_LIBELF_H=1 -DHAVE_LIMITS=1 -DHAVE_MAP=1 -DHAVE_MEMORY=1 -DHAVE_QUEUE=1 -DHAVE_SET=1 -DHAVE_STACK=1 -DHAVE_STRING=1 -DHAVE_STRINGS_H=1 -DHAVE_TYPE_TRAITS=1 -DHAVE_UNISTD_H=1 -DHAVE_UNORDERED_MAP=1 -DHAVE_UNORDERED_SET=1 -DHAVE_UTILITY=1 -DHAVE_VECTOR=1 -DHAVE_ELF_H=1 -DHAVE_LIBELF_H=1 -DHAVE__LIBALLOCS_CONTRIB_LIBDWARFPP_CONTRIB_LIBDWARF_PREFIX_INCLUDE_DWARF_H=1 -DHAVE__LIBALLOCS_CONTRIB_LIBDWARFPP_CONTRIB_LIBDWARF_PREFIX_INCLUDE_LIBDWARF_H=1 "-DHAVE_BOOST=/**/" -DHAVE_LIBBOOST_IOSTREAMS=1 -DHAVE_LIBBOOST_REGEX=1 -DHAVE_LIBBOOST_SERIALIZATION=1 -DHAVE_LIBBOOST_SYSTEM=1 -I. -fno-omit-frame-pointer -std=c++14 -ggdb3 -fvar-tracking-assignments -O2 -fkeep-inline-functions -Wall -Wno-deprecated-declarations -Iinclude -Iinclude/dwarfpp -I/liballocs/contrib/libdwarfpp/contrib/libsrk31c++/include -I/liballocs/contrib/libdwarfpp/contrib/libc++fileno/include -I/liballocs/contrib/libdwarfpp/contrib/libdwarf/prefix/include -std=c++14 -I/liballocs/contrib/usr/include -MT src/dies.lo -MD -MP -MF src/.deps/dies.Tpo -c src/dies.cpp  -fPIC -DPIC -o src/.libs/dies.o

(deleted warnings)

src/dies.cpp: In member function 'virtual dwarf::spec::opt<dwarf::core::type_scc_t> dwarf::core::type_die::get_scc() const':
src/dies.cpp:2560:62: error: no matching function for call to 'dwarf::spec::opt<std::shared_ptr<dwarf::core::type_scc_t> >::opt(std::shared_ptr<dwarf::core::type_scc_t>)'
       = opt<shared_ptr<type_scc_t> >(shared_ptr<type_scc_t>());
                                                              ^
(deleted warnings)

Makefile:695: recipe for target 'src/dies.lo' failed
make[1]: Leaving directory '/liballocs/contrib/libdwarfpp'
make[1]: *** [src/dies.lo] Error 1
make: *** [build-libdwarfpp] Error 2
Makefile:85: recipe for target 'build-libdwarfpp' failed
make: Leaving directory '/liballocs/contrib'
The command '/bin/sh -c cd liballocs &&    git submodule init &&    git submodule update &&    make -C contrib -j1' returned a non-zero code: 2
Makefile:13: recipe for target 'build' failed
make: *** [build] Error 2
```
Do you have an idea what goes wrong? The version of GCC is gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0.

**Comment by stephenrkell** [comment]
Hi Manuel. Please try pulling the latest revision of libdwarfpp into the contrib/libdwarfpp submodule and retrying.

**Comment by mrigger** [comment]
Thanks, pulling worked but I get another error:
```
checking for /usr/include/dwarf.h... no
configure: error: in `/liballocs/contrib/libdwarfpp':
configure: error: required headers: dwarf.h (looked in /usr/include)
See `config.log' for more details
make: *** [libdwarfpp/config.status] Error 1
Makefile:79: recipe for target 'libdwarfpp/config.status' failed
make: Leaving directory '/liballocs/contrib'
The command '/bin/sh -c cd liballocs && make -C contrib -j1' returned a non-zero code: 2
Makefile:13: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by stephenrkell** [comment]
What command is this the output of? Run from what directory?

It looks like you are trying to configure libdwarfpp yourself. If so, you shouldn't do that; let liballocs's contrib/Makefile do it for you. It will (or "should"!) configure the appropriate path for finding libdwarf.h, using the libdwarf submodule in libdwarfpp (not liballocs; note that there are multiple levels of contrib/* at work).

**Comment by mrigger** [comment]
This is the `Dockerfile` that I used:
```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y bison flex texinfo git build-essential
RUN git clone https://github.com/stephenrkell/binutils-gdb.git
RUN cd binutils-gdb && \
   chmod +x configure && \
   CFLAGS="-fPIC -g -O2" ./configure --prefix=/usr/local \
     --enable-gold --enable-plugins --enable-install-libiberty && \
   make -j4 && make install
RUN apt-get update && \
   apt-get install -y libelf-dev \
       autoconf automake libtool pkg-config autoconf-archive \
       g++ ocaml ocaml-findlib \
       default-jre-headless \
       make git gawk gdb \
       libunwind-dev libc6-dev-i386 zlib1g-dev libc6-dbg \
       libboost-iostreams-dev libboost-regex-dev libboost-serialization-dev libboost-filesystem-dev
RUN git clone https://github.com/stephenrkell/liballocs.git
RUN apt-get update && apt-get install -y python
RUN cd liballocs && \
   git submodule init && \
   git submodule update
RUN cd /liballocs/contrib/libdwarfpp && git pull https://github.com/stephenrkell/libdwarfpp
RUN cd liballocs && make -C contrib -j1
```
The errors occurs when calling `make` in the `contrib` directory.

**Comment by stephenrkell** [comment]
OK, the problem was in the case where /usr/include/{lib,}dwarf.h were not present in the build environment. I've just pushed a new commit to libdwarfpp which seems to fix this. Please let me know how you get on.

**Comment by mrigger** [comment]
Thanks! That seems to work now. However, with the Dockerfile above, I still get an error in the `make` step:

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../binutils-2.26/bfd -I. -I../../binutils-2.26/bfd -I../../binutils-2.26/bfd/../include -DHAVE_x86_64_elf64_vec -DHAVE_i386_elf32_vec -DHAVE_iamcu_elf32_vec -DHAVE_x86_64_elf32_vec -DHAVE_i386_aout_linux_vec -DHAVE_i386_pei_vec -DHAVE_x86_64_pei_vec -DHAVE_l1om_elf64_vec -DHAVE_k1om_elf64_vec -DHAVE_elf64_le_vec -DHAVE_elf64_be_vec -DHAVE_elf32_le_vec -DHAVE_elf32_be_vec -DHAVE_plugin_vec -DBINDIR=\"/liballocs/contrib/trap-syscalls/contrib/bin\" -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Werror -I../../binutils-2.26/bfd/../zlib -g -O2 -fPIC -MT reloc.lo -MD -MP -MF .deps/reloc.Tpo -c ../../binutils-2.26/bfd/reloc.c -o reloc.o
In file included from ../../binutils-2.26/bfd/reloc.c:52:0:
../../binutils-2.26/bfd/reloc.c: In function 'bfd_default_reloc_type_lookup':
../../binutils-2.26/bfd/libbfd.h:769:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
   do { bfd_assert(__FILE__,__LINE__); } while (0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../binutils-2.26/bfd/reloc.c:7724:4: note: in expansion of macro 'BFD_FAIL'
    BFD_FAIL ();
    ^~~~~~~~
../../binutils-2.26/bfd/reloc.c:7725:2: note: here
  case 32:
  ^~~~
In file included from ../../binutils-2.26/bfd/reloc.c:52:0:
../../binutils-2.26/bfd/libbfd.h:769:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
   do { bfd_assert(__FILE__,__LINE__); } while (0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../binutils-2.26/bfd/reloc.c:7728:4: note: in expansion of macro 'BFD_FAIL'
    BFD_FAIL ();
    ^~~~~~~~
../../binutils-2.26/bfd/reloc.c:7729:2: note: here
  default:
  ^~~~~~~
In file included from ../../binutils-2.26/bfd/reloc.c:52:0:
../../binutils-2.26/bfd/libbfd.h:769:8: error: this statement may fall through [-Werror=implicit-fallthrough=]
   do { bfd_assert(__FILE__,__LINE__); } while (0)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../binutils-2.26/bfd/reloc.c:7730:4: note: in expansion of macro 'BFD_FAIL'
    BFD_FAIL ();
    ^~~~~~~~
../../binutils-2.26/bfd/reloc.c:7732:5: note: here
     default:
     ^~~~~~~
cc1: all warnings being treated as errors
Makefile:1631: recipe for target 'reloc.lo' failed
make[6]: Leaving directory '/liballocs/contrib/trap-syscalls/contrib/binutils-build/bfd'
make[6]: *** [reloc.lo] Error 1
Makefile:1673: recipe for target 'all-recursive' failed
make[5]: Leaving directory '/liballocs/contrib/trap-syscalls/contrib/binutils-build/bfd'
make[5]: *** [all-recursive] Error 1
Makefile:1152: recipe for target 'all' failed
make[4]: Leaving directory '/liballocs/contrib/trap-syscalls/contrib/binutils-build/bfd'
make[4]: *** [all] Error 2
Makefile:2711: recipe for target 'all-bfd' failed
make[3]: Leaving directory '/liballocs/contrib/trap-syscalls/contrib/binutils-build'
make[3]: *** [all-bfd] Error 2
Makefile:845: recipe for target 'all' failed
make[2]: Leaving directory '/liballocs/contrib/trap-syscalls/contrib/binutils-build'
make[2]: *** [all] Error 2
Makefile:115: recipe for target 'build-binutils' failed
make[1]: Leaving directory '/liballocs/contrib/trap-syscalls/contrib'
make[1]: *** [build-binutils] Error 2
make: *** [trap-syscalls/contrib/config.mk] Error 2
Makefile:172: recipe for target 'trap-syscalls/contrib/config.mk' failed
make: Leaving directory '/liballocs/contrib'
The command '/bin/sh -c cd liballocs && make -C contrib -j1' returned a non-zero code: 2
Makefile:13: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by stephenrkell** [comment]
OK. That is in the trap-syscalls submodule. It is caused by building an old binutils on a too-new compiler. You can either use an older compiler that doesn't flag fallthrough with -Werror (e.g. by changing your Docker file to an older distro) or skip the binutils build.

The latter will be easier. It turns out that I've already applied this change in trap-syscalls. So, much like you did with libdwarfpp, try something like this in your Dockerfile.

RUN cd /liballocs/contrib/trap-syscalls && git pull https://github.com/stephenrkell/trap-syscalls

**Comment by mrigger** [comment]
I tried modifying the Dockerfile as you suggested (see below), but the error remains.

```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y bison flex texinfo git build-essential
RUN git clone https://github.com/stephenrkell/binutils-gdb.git
RUN cd binutils-gdb && \
   chmod +x configure && \
   CFLAGS="-fPIC -g -O2" ./configure --prefix=/usr/local \
     --enable-gold --enable-plugins --enable-install-libiberty && \
   make -j4 && make install
RUN apt-get update && \
   apt-get install -y libelf-dev \
       autoconf automake libtool pkg-config autoconf-archive \
       g++ ocaml ocaml-findlib \
       default-jre-headless \
       make git gawk gdb \
       libunwind-dev libc6-dev-i386 zlib1g-dev libc6-dbg \
       libboost-iostreams-dev libboost-regex-dev libboost-serialization-dev libboost-filesystem-dev wget
RUN git clone https://github.com/stephenrkell/liballocs.git
RUN apt-get update && apt-get install -y python
RUN cd liballocs && \
   git submodule init && \
   git submodule update
RUN cd /liballocs/contrib/libdwarfpp && git pull https://github.com/stephenrkell/libdwarfpp
RUN cd /liballocs/contrib/trap-syscalls && git pull https://github.com/stephenrkell/trap-syscalls
RUN cd liballocs && make -C contrib -j1
``

**Comment by stephenrkell** [comment]
I believe the build is now fixed, as of 1294edf. A few of the build steps have changed (see the new README) but I've had success with the following Dockerfile.

```
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y bison flex texinfo git build-essential
RUN git clone https://github.com/stephenrkell/binutils-gdb.git
RUN cd binutils-gdb && \
   chmod +x configure && \
   CFLAGS="-fPIC -g -O2" ./configure --prefix=/usr/local \
     --enable-gold --enable-plugins --enable-install-libiberty && \
   make -j4 && make install
RUN apt-get update && \
   apt-get install -y libelf-dev libdw-dev \
       autoconf automake libtool pkg-config autoconf-archive \
       g++ ocaml ocamlbuild ocaml-findlib \
       default-jre-headless \
       make git gawk gdb wget \
       libunwind-dev libc6-dev-i386 zlib1g-dev libc6-dbg \
       libboost-iostreams-dev libboost-regex-dev libboost-serialization-dev libboost-filesystem-dev
RUN git clone https://github.com/stephenrkell/liballocs.git
RUN apt-get update && apt-get install -y python
RUN cd liballocs && \
   git submodule update --init --recursive && \
   make -C contrib -j1
RUN cd liballocs && \
   ./autogen.sh && \
   (. contrib/env.sh && ./configure --prefix=/usr/local) && \
   make
```

One caveat to that "success" though: there is a (suspected) compiler bug in g++ 7.3.0, which miscompiles some boost::optional-using code. So you will still encounter problems with this particular build (building liballocs/src/uniqtypes.o). Probably a different version of gcc and/or boost will do the trick. I haven't yet had time to produce a workaround.

(What I suspect will work: in tools/uniqtypes.o, replace uses of optional<const string&> with optional<string>.)

**Comment by stephenrkell** [comment]
I've now applied this change, in b26050a. Seems to work, though I've only tried it with the gcc in Debian.

I will commit some working Dockerfiles for at least these two distributions soon (since I broke the Debian jessie/stretch build when I made it work for Ubuntu 18.04).

**Comment by mrigger** [comment]
Thank you for the changes and your patience! The Dockerfile seems to now build successfully.
